allowBuilds:
  core-js-pure: true
  esbuild: true
  workerd: true
overrides:
  "@cloudflare/kumo>zod": "^3.25.76"
  "@tiptap/core": "3.20.2"
  "@tiptap/extension-blockquote": "3.20.2"
  "@tiptap/extension-bold": "3.20.2"
  "@tiptap/extension-bubble-menu": "3.20.2"
  "@tiptap/extension-bullet-list": "3.20.2"
  "@tiptap/extension-code": "3.20.2"
  "@tiptap/extension-code-block": "3.20.2"
  "@tiptap/extension-document": "3.20.2"
  "@tiptap/extension-dropcursor": "3.20.2"
  "@tiptap/extension-floating-menu": "3.20.2"
  "@tiptap/extension-gapcursor": "3.20.2"
  "@tiptap/extension-hard-break": "3.20.2"
  "@tiptap/extension-heading": "3.20.2"
  "@tiptap/extension-horizontal-rule": "3.20.2"
  "@tiptap/extension-italic": "3.20.2"
  "@tiptap/extension-list": "3.20.2"
  "@tiptap/extension-list-item": "3.20.2"
  "@tiptap/extension-list-keymap": "3.20.2"
  "@tiptap/extension-ordered-list": "3.20.2"
  "@tiptap/extension-paragraph": "3.20.2"
  "@tiptap/extension-strike": "3.20.2"
  "@tiptap/extension-text": "3.20.2"
  "@tiptap/extensions": "3.20.2"
  "@tiptap/pm": "3.20.2"
